#!/bin/bash
# update_nav.sh - Regenerates NAV_MAP.md from references/ directory
# Run after git pull to keep the navigation map current.
#
# Usage: ./update_nav.sh
# Or from repo root: ./jek__skills/datadog-documentation/update_nav.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REFS_DIR="$SCRIPT_DIR/references"
NAV_MAP="$REFS_DIR/NAV_MAP.md"

# Mode roots to index (grouped by mode)
# Mode 1: Agent & Infrastructure
# Mode 2: SDK & Tracing
# Mode 3: Session Monitoring
# Mode 4: CloudPrem
# Also includes cross-cutting roots useful across modes
MODE_ROOTS=(
  "agent"
  "infrastructure"
  "integrations"
  "containers"
  "serverless"
  "network_monitoring"
  "opentelemetry"
  "tracing"
  "profiler"
  "data_streams"
  "error_tracking"
  "product_analytics"
  "real_user_monitoring"
  "session_replay"
  "synthetics"
  "mobile"
  "cloudprem"
  "logs"
  "getting_started"
)

{
  echo "# NAV_MAP - Auto-generated by update_nav.sh. Do not edit manually."
  echo "# Format: relative_path | title"
  echo "# Generated: $(date +%Y-%m-%d)"
  echo ""

  for root in "${MODE_ROOTS[@]}"; do
    root_dir="$REFS_DIR/$root"
    if [ ! -d "$root_dir" ]; then
      continue
    fi

    echo "## $root"

    find "$root_dir" -name "_index.md" -type f | sort | while IFS= read -r f; do
      relpath="${f#"$REFS_DIR"/}"
      relpath="${relpath%/_index.md}"

      title=$(head -10 "$f" | grep -m1 "^title:" | sed 's/^title: *//; s/^"//; s/"$//; s/^'\''//; s/'\''$//')

      if [ -z "$title" ]; then
        title=$(basename "$relpath")
      fi

      echo "$relpath | $title"
    done

    echo ""
  done
} > "$NAV_MAP"

entries=$(grep -c '|' "$NAV_MAP")
echo "NAV_MAP.md generated at: $NAV_MAP"
echo "Entries: $entries sections indexed"
